include:
  - redis-server.yaml

services:
  api:
    build:        
      context: ./api
      dockerfile: api.Dockerfile
    environment:
      - FRONT_URL=http://localhost:7070
      # to allow the front to connect to the API (CORS, Cross-Origin Resource Sharing)
    ports:
      - 6060:8080
      # query the API on http://localhost:6060/counter
    depends_on:
      redis-server:
        condition: service_started
    networks:
      - backend
      - frontend

  webapp:
    build:        
      context: ./web
      dockerfile: web.Dockerfile
    environment:
      - API_URL=http://localhost:6060
    # docker compose watch
    develop:
      watch:
        - action: sync
          path: web/templates
          target: app/templates
    ports:
      - 7070:8080
      # open the webapp http://localhost:7070/
    depends_on:
      api:
        condition: service_started
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  redis-data:
    external: true

# https://docs.docker.com/compose/compose-file/compose-file-v2/#external